/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;
import Model.Imovel;
import java.util.Enumeration;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
/**
 *
 * @author wagner
 * @author denner
 */
public class FormCadastroImoveis extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormCadastroImoveis() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jExit = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_Endereco = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtf_Cep = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jcb_estado = new javax.swing.JComboBox<>();
        jl_Estado = new javax.swing.JLabel();
        jtf_Cidade = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtf_Complemento = new javax.swing.JTextField();
        jl_Complemento = new javax.swing.JLabel();
        jtf_Bairro = new javax.swing.JTextField();
        jl_Bairro = new javax.swing.JLabel();
        jtf_Endereco = new javax.swing.JTextField();
        jl_Endereco = new javax.swing.JLabel();
        jtf_NomeImov = new javax.swing.JTextField();
        jPanel_Casa = new javax.swing.JPanel();
        jl_quarto = new javax.swing.JLabel();
        jl_Sala = new javax.swing.JLabel();
        jl_banheiro = new javax.swing.JLabel();
        jl_Picina = new javax.swing.JLabel();
        jl_Jardim = new javax.swing.JLabel();
        jl_Quintal = new javax.swing.JLabel();
        jl_QuadraEsp = new javax.swing.JLabel();
        jl_Garagem = new javax.swing.JLabel();
        jl_Porao = new javax.swing.JLabel();
        jl_Cozinha = new javax.swing.JLabel();
        jl_AreaServi = new javax.swing.JLabel();
        jl_terraço = new javax.swing.JLabel();
        jftf_Sala = new javax.swing.JFormattedTextField();
        jftf_Quarto = new javax.swing.JFormattedTextField();
        jftf_Cozinha = new javax.swing.JFormattedTextField();
        jftf_Garagem = new javax.swing.JFormattedTextField();
        jftf_Banheiro = new javax.swing.JFormattedTextField();
        jftf_Quintal = new javax.swing.JFormattedTextField();
        jl_metrosQua = new javax.swing.JLabel();
        jftf_Jardim = new javax.swing.JFormattedTextField();
        jl_metrosQua1 = new javax.swing.JLabel();
        jftf_Porão = new javax.swing.JFormattedTextField();
        jl_metrosQua2 = new javax.swing.JLabel();
        jftf_Terraço = new javax.swing.JFormattedTextField();
        jl_metrosQua3 = new javax.swing.JLabel();
        jftf_AreaSer = new javax.swing.JFormattedTextField();
        jl_metrosQua4 = new javax.swing.JLabel();
        jftf_Picina = new javax.swing.JFormattedTextField();
        jl_metrosQua5 = new javax.swing.JLabel();
        jftf_Quadra = new javax.swing.JFormattedTextField();
        jl_metrosQua6 = new javax.swing.JLabel();
        jl_VagaGar = new javax.swing.JLabel();
        jl_QuantidadeCozi = new javax.swing.JLabel();
        jl_Quantidade1 = new javax.swing.JLabel();
        jl_QuantidadeQuar = new javax.swing.JLabel();
        jl_QuantidadeSala = new javax.swing.JLabel();
        jl_Escada = new javax.swing.JLabel();
        jrb_Escada = new javax.swing.JRadioButton();
        jl_Elevador = new javax.swing.JLabel();
        jrb_Elevador = new javax.swing.JRadioButton();
        jftf_Andar = new javax.swing.JFormattedTextField();
        jl_QuantidadeAndars = new javax.swing.JLabel();
        jl_Andares = new javax.swing.JLabel();
        jl_Varanda = new javax.swing.JLabel();
        jftf_VarandaPre = new javax.swing.JFormattedTextField();
        jl_metrosQua11 = new javax.swing.JLabel();
        jcb_casa = new javax.swing.JCheckBox();
        jcb_Apartamento = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jcb_Aluguel = new javax.swing.JCheckBox();
        jcb_Compra = new javax.swing.JCheckBox();
        jPanel_Descrição = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        BTN_CASA = new javax.swing.JButton();
        jbt_Apar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Imoveis");

        jExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Logout-48.png"))); // NOI18N
        jExit.setFocusable(false);
        jExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel_Endereco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setText("Nome do imovel:");

        try {
            jtf_Cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("CEP:");

        jcb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        jl_Estado.setText("Estado:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Cidade:");

        jl_Complemento.setText("Complemento:");

        jtf_Bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_BairroActionPerformed(evt);
            }
        });

        jl_Bairro.setText("Bairro:");

        jl_Endereco.setText("Endereco:");

        javax.swing.GroupLayout jPanel_EnderecoLayout = new javax.swing.GroupLayout(jPanel_Endereco);
        jPanel_Endereco.setLayout(jPanel_EnderecoLayout);
        jPanel_EnderecoLayout.setHorizontalGroup(
            jPanel_EnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_EnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_EnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_EnderecoLayout.createSequentialGroup()
                        .addGroup(jPanel_EnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_Bairro)
                            .addComponent(jl_Complemento))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel_EnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_Complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_EnderecoLayout.createSequentialGroup()
                        .addGroup(jPanel_EnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jl_Endereco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_EnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_Endereco)
                            .addComponent(jtf_NomeImov))
                        .addGap(46, 46, 46))
                    .addGroup(jPanel_EnderecoLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(jtf_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_Cep, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel_EnderecoLayout.createSequentialGroup()
                        .addComponent(jl_Estado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel_EnderecoLayout.setVerticalGroup(
            jPanel_EnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_EnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_EnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtf_NomeImov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel_EnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Endereco))
                .addGap(40, 40, 40)
                .addGroup(jPanel_EnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Bairro)
                    .addComponent(jtf_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel_EnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Complemento)
                    .addComponent(jtf_Complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel_EnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtf_Cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(39, 39, 39)
                .addGroup(jPanel_EnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Estado)
                    .addComponent(jcb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );

        jTabbedPane1.addTab("Endereço", jPanel_Endereco);

        jl_quarto.setText("Quartos");

        jl_Sala.setText("Sala");

        jl_banheiro.setText("Banheiro");

        jl_Picina.setText("Picina");

        jl_Jardim.setText("Jardim");

        jl_Quintal.setText("Quintal");

        jl_QuadraEsp.setText("Quadra de esporte");

        jl_Garagem.setText("Garagem");

        jl_Porao.setText("Porão");

        jl_Cozinha.setText("Cozinha");

        jl_AreaServi.setText("Area de serviço");

        jl_terraço.setText("Terraço");

        try {
            jftf_Sala.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jftf_Quarto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jftf_Cozinha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jftf_Garagem.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jftf_Banheiro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jftf_Quintal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jl_metrosQua.setText("M²");

        try {
            jftf_Jardim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jl_metrosQua1.setText("M²");

        try {
            jftf_Porão.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jl_metrosQua2.setText("M²");

        try {
            jftf_Terraço.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jl_metrosQua3.setText("M²");

        try {
            jftf_AreaSer.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jl_metrosQua4.setText("M²");

        try {
            jftf_Picina.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jl_metrosQua5.setText("M²");

        try {
            jftf_Quadra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jl_metrosQua6.setText("M²");

        jl_VagaGar.setText("Vagas");

        jl_QuantidadeCozi.setText("Quantidade");

        jl_Quantidade1.setText("Quantidade");

        jl_QuantidadeQuar.setText("Quantidade");

        jl_QuantidadeSala.setText("Quantidade");

        jl_Escada.setText("Escada");

        buttonGroup1.add(jrb_Escada);
        jrb_Escada.setText("Sim");

        jl_Elevador.setText("Elevador");

        buttonGroup1.add(jrb_Elevador);
        jrb_Elevador.setText("Sim");

        try {
            jftf_Andar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jl_QuantidadeAndars.setText("Quantidade");

        jl_Andares.setText("Andares");

        jl_Varanda.setText("Varanda");

        try {
            jftf_VarandaPre.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jl_metrosQua11.setText("M²");

        jcb_casa.setText("Casa");
        jcb_casa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_casaActionPerformed(evt);
            }
        });

        jcb_Apartamento.setText("Apartamento");
        jcb_Apartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_ApartamentoActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo do contrato");

        jcb_Aluguel.setText("Aluguel");

        jcb_Compra.setText("Compra");

        javax.swing.GroupLayout jPanel_CasaLayout = new javax.swing.GroupLayout(jPanel_Casa);
        jPanel_Casa.setLayout(jPanel_CasaLayout);
        jPanel_CasaLayout.setHorizontalGroup(
            jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CasaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_CasaLayout.createSequentialGroup()
                        .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_CasaLayout.createSequentialGroup()
                                .addComponent(jl_banheiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jftf_Banheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jl_Quantidade1))
                            .addGroup(jPanel_CasaLayout.createSequentialGroup()
                                .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_Garagem)
                                    .addComponent(jl_Porao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_CasaLayout.createSequentialGroup()
                                        .addComponent(jftf_Garagem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jl_VagaGar))
                                    .addGroup(jPanel_CasaLayout.createSequentialGroup()
                                        .addComponent(jftf_Porão, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jl_metrosQua2))))
                            .addGroup(jPanel_CasaLayout.createSequentialGroup()
                                .addComponent(jl_Elevador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrb_Elevador))
                            .addGroup(jPanel_CasaLayout.createSequentialGroup()
                                .addComponent(jl_Escada)
                                .addGap(24, 24, 24)
                                .addComponent(jrb_Escada))
                            .addGroup(jPanel_CasaLayout.createSequentialGroup()
                                .addComponent(jl_Andares)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jftf_Andar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jl_QuantidadeAndars))
                            .addGroup(jPanel_CasaLayout.createSequentialGroup()
                                .addComponent(jl_Sala)
                                .addGap(43, 43, 43)
                                .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcb_casa)
                                    .addGroup(jPanel_CasaLayout.createSequentialGroup()
                                        .addComponent(jftf_Sala, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jl_QuantidadeSala)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_CasaLayout.createSequentialGroup()
                                .addComponent(jl_Picina)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jftf_Picina, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jl_metrosQua5))
                            .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel_CasaLayout.createSequentialGroup()
                                    .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jl_Jardim)
                                        .addComponent(jl_Quintal))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jftf_Jardim, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jftf_Quintal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jl_metrosQua1)
                                        .addComponent(jl_metrosQua)))
                                .addGroup(jPanel_CasaLayout.createSequentialGroup()
                                    .addComponent(jl_terraço)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jftf_Terraço, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jl_metrosQua3)))
                            .addGroup(jPanel_CasaLayout.createSequentialGroup()
                                .addComponent(jl_AreaServi)
                                .addGap(52, 52, 52)
                                .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_CasaLayout.createSequentialGroup()
                                        .addComponent(jftf_Quadra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jl_metrosQua6))
                                    .addGroup(jPanel_CasaLayout.createSequentialGroup()
                                        .addComponent(jftf_AreaSer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jl_metrosQua4))))
                            .addComponent(jl_QuadraEsp)
                            .addGroup(jPanel_CasaLayout.createSequentialGroup()
                                .addComponent(jl_Varanda)
                                .addGap(102, 102, 102)
                                .addComponent(jl_metrosQua11))
                            .addGroup(jPanel_CasaLayout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jftf_VarandaPre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jcb_Apartamento)
                            .addComponent(jLabel3)
                            .addGroup(jPanel_CasaLayout.createSequentialGroup()
                                .addComponent(jcb_Aluguel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcb_Compra)))
                        .addContainerGap(13, Short.MAX_VALUE))
                    .addGroup(jPanel_CasaLayout.createSequentialGroup()
                        .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_CasaLayout.createSequentialGroup()
                                .addComponent(jl_quarto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jftf_Quarto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jl_QuantidadeQuar))
                            .addGroup(jPanel_CasaLayout.createSequentialGroup()
                                .addComponent(jl_Cozinha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jftf_Cozinha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jl_QuantidadeCozi)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel_CasaLayout.setVerticalGroup(
            jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CasaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_casa)
                    .addComponent(jcb_Apartamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jftf_Terraço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jl_metrosQua3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jl_terraço))
                    .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jl_Sala)
                        .addComponent(jftf_Sala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jl_QuantidadeSala, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_CasaLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_quarto)
                            .addComponent(jftf_Quarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_QuantidadeQuar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_Cozinha)
                            .addComponent(jftf_Cozinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_QuantidadeCozi, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_CasaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_Quintal)
                            .addGroup(jPanel_CasaLayout.createSequentialGroup()
                                .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jftf_Quintal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jl_metrosQua, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jftf_Jardim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jl_metrosQua1)
                                    .addComponent(jl_Jardim))))))
                .addGap(18, 18, 18)
                .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jl_Picina)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CasaLayout.createSequentialGroup()
                            .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jftf_Picina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jl_metrosQua5))
                            .addGap(1, 1, 1)))
                    .addGroup(jPanel_CasaLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_banheiro)
                            .addComponent(jftf_Banheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_Quantidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_CasaLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_Andares)
                            .addComponent(jftf_Andar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_QuantidadeAndars))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_Garagem)
                            .addComponent(jftf_Garagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_VagaGar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jftf_Porão, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_metrosQua2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_Porao))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrb_Escada)
                            .addComponent(jl_Escada))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_Elevador)
                            .addComponent(jrb_Elevador)))
                    .addGroup(jPanel_CasaLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_Varanda)
                            .addComponent(jftf_VarandaPre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_metrosQua11))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_QuadraEsp)
                            .addComponent(jftf_Quadra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_metrosQua6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_AreaServi)
                            .addComponent(jftf_AreaSer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_metrosQua4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_CasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcb_Aluguel)
                            .addComponent(jcb_Compra))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Imovel", jPanel_Casa);

        jLabel2.setText("Descrição imovel:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel_DescriçãoLayout = new javax.swing.GroupLayout(jPanel_Descrição);
        jPanel_Descrição.setLayout(jPanel_DescriçãoLayout);
        jPanel_DescriçãoLayout.setHorizontalGroup(
            jPanel_DescriçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_DescriçãoLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel_DescriçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel_DescriçãoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(428, 428, 428)))
                .addContainerGap())
        );
        jPanel_DescriçãoLayout.setVerticalGroup(
            jPanel_DescriçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_DescriçãoLayout.createSequentialGroup()
                .addContainerGap(191, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );

        jTabbedPane1.addTab("Descrição", jPanel_Descrição);

        jLabel4.setText("Dados do Imovel");

        BTN_CASA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/House-48.png"))); // NOI18N
        BTN_CASA.setText("Casa");
        BTN_CASA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CASAActionPerformed(evt);
            }
        });

        jbt_Apar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Building-Add-48.png"))); // NOI18N
        jbt_Apar.setText("Apartamento");
        jbt_Apar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_AparActionPerformed(evt);
            }
        });

        jMenu1.setText("Cadrastro");

        jMenuItem1.setText("Novo Imovel");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(BTN_CASA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbt_Apar, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(jExit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(272, 272, 272))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jExit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_CASA, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_Apar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        this.dispose();
      
    }//GEN-LAST:event_jExitActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void BTN_CASAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CASAActionPerformed
        // TODO add your handling code here:
        Imovel imovel = new Imovel();
        // endereco
        imovel.setNome(jtf_NomeImov.getText());
        imovel.getEndereco().setLogradouro(jtf_Endereco.getText());
        imovel.getEndereco().setBairro(jtf_Bairro.getText());
        imovel.getEndereco().setComplemento(jtf_Complemento.getText());
        imovel.getEndereco().setCidade(jtf_Cidade.getText());
        imovel.getEndereco().setCep(jtf_Cep.getText());
        imovel.getEndereco().setEstado(jcb_estado.getSelectedItem().toString());
        //casa
            imovel.setSala(jftf_Sala.getText());
            imovel.setQuartos(jftf_Quarto.getText());
            imovel.setCozinha(jftf_Cozinha.getText());
            imovel.setBanheiro(jftf_Banheiro.getText());
            imovel.setGaragem(jftf_Garagem.getText());
            imovel.setPorao(jftf_Porão.getText());
            imovel.setTerraco(jftf_Terraço.getText());
            imovel.setQuital(jftf_Quintal.getText());
            imovel.setJardim(jftf_Jardim.getText());
            imovel.setPicina(jftf_Picina.getText());
            imovel.setQuadraEsporte(jftf_Quadra.getText());
            imovel.setAreaServico(jftf_AreaSer.getText());
        
       // tipo do contrato
       jcb_Aluguel.isSelected();
       jcb_Compra.isSelected();
        
        JRadioButton radio;
          String str;
          Enumeration jr = buttonGroup1.getElements();
             while ( jr.hasMoreElements() )
              {
                    radio = (JRadioButton) jr.nextElement();
                    if (radio.isSelected())
                      {
                           str = radio.getText();
                      }
               }
        
        FormPrincipal.daoImovel.inserirImovel(imovel);
        JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso!");
    }//GEN-LAST:event_BTN_CASAActionPerformed

    private void jtf_BairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_BairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_BairroActionPerformed

    private void jbt_AparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_AparActionPerformed
        // TODO add your handling code here:
        Imovel imovel = new Imovel(); 
        //predio
      
        imovel.setAndar(jftf_Andar.getText());
        imovel.setEscada(buttonGroup1.getSelection().getActionCommand());
        imovel.setElevador(buttonGroup1.getSelection().getActionCommand()); // sera?
        imovel.setVaranda(jftf_VarandaPre.getText());
        
    }//GEN-LAST:event_jbt_AparActionPerformed

    private void jcb_casaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_casaActionPerformed
        // TODO add your handling code here:
          if(!jcb_casa.isSelected()){
            jbt_Apar.setEnabled(true);
          }else
          {
              jbt_Apar.setEnabled(false);
              jftf_Porão.setEnabled(true);
              jrb_Elevador.setEnabled(false);
              BTN_CASA.requestFocus();
          }          
    }//GEN-LAST:event_jcb_casaActionPerformed

    private void jcb_ApartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_ApartamentoActionPerformed
        // TODO add your handling code here:
         if(!jcb_Apartamento.isSelected()){
            BTN_CASA.setEnabled(true);
          }else
          {
              BTN_CASA.setEnabled(false);
              jftf_Porão.setEnabled(false);
              jrb_Elevador.setEnabled(true);
              jbt_Apar.requestFocus();
          }
    }//GEN-LAST:event_jcb_ApartamentoActionPerformed

       public void cadastrarImoveis()
       {
           Imovel imovel = null;
           for(int i=1; i<10; i++)
           {
               imovel = new Imovel();
               imovel.setNumeroImovel(1000+i);
               imovel.setNome("fulando"+i);
               
           }
               
       }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastroImoveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastroImoveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastroImoveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastroImoveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastroImoveis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_CASA;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel_Casa;
    private javax.swing.JPanel jPanel_Descrição;
    private javax.swing.JPanel jPanel_Endereco;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbt_Apar;
    private javax.swing.JCheckBox jcb_Aluguel;
    private javax.swing.JCheckBox jcb_Apartamento;
    private javax.swing.JCheckBox jcb_Compra;
    private javax.swing.JCheckBox jcb_casa;
    private javax.swing.JComboBox<String> jcb_estado;
    private javax.swing.JFormattedTextField jftf_Andar;
    private javax.swing.JFormattedTextField jftf_AreaSer;
    private javax.swing.JFormattedTextField jftf_Banheiro;
    private javax.swing.JFormattedTextField jftf_Cozinha;
    private javax.swing.JFormattedTextField jftf_Garagem;
    private javax.swing.JFormattedTextField jftf_Jardim;
    private javax.swing.JFormattedTextField jftf_Picina;
    private javax.swing.JFormattedTextField jftf_Porão;
    private javax.swing.JFormattedTextField jftf_Quadra;
    private javax.swing.JFormattedTextField jftf_Quarto;
    private javax.swing.JFormattedTextField jftf_Quintal;
    private javax.swing.JFormattedTextField jftf_Sala;
    private javax.swing.JFormattedTextField jftf_Terraço;
    private javax.swing.JFormattedTextField jftf_VarandaPre;
    private javax.swing.JLabel jl_Andares;
    private javax.swing.JLabel jl_AreaServi;
    private javax.swing.JLabel jl_Bairro;
    private javax.swing.JLabel jl_Complemento;
    private javax.swing.JLabel jl_Cozinha;
    private javax.swing.JLabel jl_Elevador;
    private javax.swing.JLabel jl_Endereco;
    private javax.swing.JLabel jl_Escada;
    private javax.swing.JLabel jl_Estado;
    private javax.swing.JLabel jl_Garagem;
    private javax.swing.JLabel jl_Jardim;
    private javax.swing.JLabel jl_Picina;
    private javax.swing.JLabel jl_Porao;
    private javax.swing.JLabel jl_QuadraEsp;
    private javax.swing.JLabel jl_Quantidade1;
    private javax.swing.JLabel jl_QuantidadeAndars;
    private javax.swing.JLabel jl_QuantidadeCozi;
    private javax.swing.JLabel jl_QuantidadeQuar;
    private javax.swing.JLabel jl_QuantidadeSala;
    private javax.swing.JLabel jl_Quintal;
    private javax.swing.JLabel jl_Sala;
    private javax.swing.JLabel jl_VagaGar;
    private javax.swing.JLabel jl_Varanda;
    private javax.swing.JLabel jl_banheiro;
    private javax.swing.JLabel jl_metrosQua;
    private javax.swing.JLabel jl_metrosQua1;
    private javax.swing.JLabel jl_metrosQua11;
    private javax.swing.JLabel jl_metrosQua2;
    private javax.swing.JLabel jl_metrosQua3;
    private javax.swing.JLabel jl_metrosQua4;
    private javax.swing.JLabel jl_metrosQua5;
    private javax.swing.JLabel jl_metrosQua6;
    private javax.swing.JLabel jl_quarto;
    private javax.swing.JLabel jl_terraço;
    private javax.swing.JRadioButton jrb_Elevador;
    private javax.swing.JRadioButton jrb_Escada;
    private javax.swing.JTextField jtf_Bairro;
    private javax.swing.JFormattedTextField jtf_Cep;
    private javax.swing.JTextField jtf_Cidade;
    private javax.swing.JTextField jtf_Complemento;
    private javax.swing.JTextField jtf_Endereco;
    private javax.swing.JTextField jtf_NomeImov;
    // End of variables declaration//GEN-END:variables
}
